version: "3"
services:
  api:
    build:
      context: ./TestePrometheusGrafana
      dockerfile: Dockerfile
      args:
        version: 1
    image: teste-prometheus-grafana-metrics
    ports:
      - 8888:8080
    networks:
      network:
        ipv4_address: 172.18.18.10
  prometheus:
    build:
      context: ./Prometheus
      dockerfile: Dockerfile
      args:
        version: 1
    image: prometheus-local
    restart: always
    ports:
      - 9090:9090
    networks:
      network:
        ipv4_address: 172.18.18.11
    volumes:
      - './prometheus/data:/data'
  grafana:
    build:
      context: ./Grafana
      dockerfile: Dockerfile
      args:
        version: 1
    image: grafana-local
    restart: always
    ports:
      - 3000:3000
    networks:
      network:
        ipv4_address: 172.18.18.12

networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: "172.18.18.0/24"
          gateway: 172.18.18.1