version: "3.8"
services:
  api:
    build:
      context: ./TestePrometheusGrafana
      dockerfile: Dockerfile
      args:
        version: 1
    image: teste-prometheus-grafana-metrics
    depends_on:
      - mysql-local
    ports:
      - 8888:8080
    networks:
      network:
        ipv4_address: 172.18.18.10
  prometheus:
    build:
      context: ./Prometheus
      dockerfile: Dockerfile
      args:
        version: 1
    image: prometheus-local
    restart: always
    ports:
      - 9090:9090
    networks:
      network:
        ipv4_address: 172.18.18.11
    volumes:
      - './Prometheus/data:/data:Z'
  grafana:
    build:
      context: ./Grafana
      dockerfile: Dockerfile
      args:
        version: 1
    image: grafana-local
    restart: always
    ports:
      - 3000:3000
    networks:
      network:
        ipv4_address: 172.18.18.12
  mysql-local:
    build:
      context: ./Mysql
      dockerfile: Dockerfile
      args:
        version: 1
    image: mysql-local
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - './Mysql/dbmysql-volume:/var/lib/mysql:Z'
    restart: always
    ports:
      - 3306:3306
    networks:
      network:
        ipv4_address: 172.18.18.13

networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: "172.18.18.0/24"
          gateway: 172.18.18.1