{
 "title": "Metricas Negocio",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "canal",
    "label": "Canal",
    "query": "label_values(BoletasCriadas, tipoCanal)"
   },
   {
    "name": "tipo_produto",
    "label": "Tipo Produto",
    "query": "label_values(BoletasCriadas, tipoBoleta)"
   },
   {
    "name": "origem_pendencia",
    "label": "Origem Pendencia",
    "query": "label_values(pendencias_transacionais, tipo_origem)"
   }
  ]
 },
 "panels": [
  {
   "title": "Boletas Movimentações",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Quantidade Boletas",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(BoletasCriadas{tipoCanal=~\"$canal\", tipoBoleta=~\"$tipo_produto\"}[1m])) by (tipoBoleta, tipoCanal)",
       "legendFormat": "{{tipoCanal}}-{{tipoBoleta}}"
      }
     ]
    },
    {
     "title": "R$ Movimentado",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(ValorBoletasCriadas{tipoCanal=~\"$canal\", tipoBoleta=~\"$tipo_produto\"}[1m])) by (tipoBoleta, tipoCanal)",
       "legendFormat": "{{tipoCanal}}-{{tipoBoleta}}"
      }
     ]
    }
   ]
  },
  { "title": "Saúde Trasacional", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Pendencias",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (rate(pendencias_transacionais{tipo_pendencia=\"Informativa\", tipoCanal=~\"$canal\", tipoBoleta=~\"$tipo_produto\", tipo_origem=~\"$origem_pendencia\"}[1m]))/sum (rate(pendencias_transacionais{tipoCanal=~\"$canal\", tipoBoleta=~\"$tipo_produto\", tipo_origem=~\"$origem_pendencia\"}[1m])) * 100",
     "legendFormat": "Informativa"
    },
    {
     "expr": "sum (rate(pendencias_transacionais{tipo_pendencia=\"Impeditiva\", tipoCanal=~\"$canal\", tipoBoleta=~\"$tipo_produto\", tipo_origem=~\"$origem_pendencia\"}[1m]))/sum (rate(pendencias_transacionais{tipoCanal=~\"$canal\", tipoBoleta=~\"$tipo_produto\", tipo_origem=~\"$origem_pendencia\"}[1m])) * 100",
     "legendFormat": "Impeditiva"
    },
    {
     "expr": "sum (rate(pendencias_transacionais{tipo_pendencia=\"Falha\", tipoCanal=~\"$canal\", tipoBoleta=~\"$tipo_produto\", tipo_origem=~\"$origem_pendencia\"}[1m]))/sum (rate(pendencias_transacionais{tipoCanal=~\"$canal\", tipoBoleta=~\"$tipo_produto\", tipo_origem=~\"$origem_pendencia\"}[1m])) * 100",
     "legendFormat": "Falha"
    }
   ]
  },
  {
   "title": "Top Produtos Falha",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(3, sum(increase(pendencias_transacionais{tipo_pendencia=\"Falha\",tipoCanal=~\"$canal\", tipo_origem=~\"$origem_pendencia\"}[$__range])) by (tipoBoleta))\n"
    }
   ]
  },
  {
   "title": "Pendencias",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(pendencias_exibidas{tipoCanal=~\"$canal\", tipoBoleta=~\"$tipo_produto\", tipo_origem=~\"$origem_pendencia\", tipo_pendencia!=\"Ok\"}[1m])) by (tipo_origem, tipo_pendencia)",
     "legendFormat": "{{tipo_origem}}-{{tipo_pendencia}}"
    }
   ]
  }
 ]
}